# Generated by Django 4.1.3 on 2022-11-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_remove_customer_latitudex_remove_customer_longitudey'),
        ('drivers', '0001_initial'),
        ('shedule', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status_order',
            },
        ),
        migrations.CreateModel(
            name='Type_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type_order',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=200)),
                ('package_value', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='drivers.driver')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.payment')),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedule', to='shedule.shedule')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='orders.status_order')),
                ('type_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_order', to='orders.type_order')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
