# Generated by Django 4.1.3 on 2022-11-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_latitude_remove_order_longitude'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationorder',
            table='location_order',
        ),
    ]
