# Generated by Django 4.1.3 on 2022-11-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='key',
            field=models.CharField(default=b'vuEdf1E9V0iAea2ccMB_LAAmZq1boYdXL0hMJ511wUU=', max_length=200),
        ),
    ]
