# Generated by Django 4.1.3 on 2022-11-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='key',
            field=models.TextField(),
        ),
    ]
