# Generated by Django 4.1.3 on 2022-11-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
