# Generated by Django 4.1.3 on 2022-11-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
