# Generated by Django 4.1.3 on 2022-11-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_is_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitudex',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitudey',
        ),
    ]
