# Generated by Django 4.1.3 on 2022-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_latitude_locationdriver_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
        migrations.AddField(
            model_name='driver',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='LocationDriver',
        ),
    ]
