# Generated by Django 4.1.3 on 2022-11-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_lastupdate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driver',
            table='drivers',
        ),
    ]
