# Generated by Django 4.1.3 on 2022-11-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_remove_driver_lat_remove_driver_lng_locationdriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='lastUpdate',
        ),
        migrations.AddField(
            model_name='locationdriver',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
