# Generated by Django 4.1.3 on 2022-11-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_email'),
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shedule', to='customers.customer'),
        ),
    ]
